# -*- coding: utf-8 -*-
# enUS translation data for BossTips.
# NAME_MAP: zh name -> en name  (instances AND bosses)
# TIP_MAP:  exact zh source tip string -> en tip string (final format)
# Only entries present here are emitted; others fall back to zhCN source.

NAME_MAP = {
    # ===== NATIVE 1.0 instances =====
    "影牙城堡": "Shadowfang Keep",
    "哀嚎洞穴": "Wailing Caverns",
    "黑暗深渊": "Blackfathom Deeps",
    "剃刀沼泽": "Razorfen Kraul",
    "诺莫瑞根": "Gnomeregan",
    "血色大厅": "Scarlet Halls",
    "祖尔法拉克": "Zul'Farrak",
    "厄运之槌": "Dire Maul",
    "黑石深渊": "Blackrock Depths",
    "斯坦索姆": "Stratholme",
    "奥达曼": "Uldaman",
    "黑石塔下层": "Lower Blackrock Spire",
    "玛拉顿": "Maraudon",
    "死亡矿井": "Deadmines",
    "血色修道院": "Scarlet Monastery",
    "通灵学院": "Scholomance",
    "怒焰裂谷": "Ragefire Chasm",
    "剃刀高地": "Razorfen Downs",
    "沉没的神庙": "Temple of Atal'Hakkar",
    "暴风城监狱": "Stormwind Stockade",
    # ===== NATIVE 2.0 instances =====
    "奥金顿：塞泰克大厅": "Auchindoun: Sethekk Halls",
    "奥金顿：法力墓穴": "Auchindoun: Mana-Tombs",
    "魔导师平台": "Magister's Terrace",
    "地狱火堡垒：鲜血熔炉": "Hellfire Citadel: The Blood Furnace",
    "风暴要塞：能源舰": "Tempest Keep: The Mechanar",
    "盘牙湖泊：奴隶围栏": "Coilfang Reservoir: The Slave Pens",
    "风暴要塞：禁魔监狱": "Tempest Keep: The Arcatraz",
    "奥金顿：奥金尼地穴": "Auchindoun: Auchenai Crypts",
    "盘牙湖泊：幽暗沼泽": "Coilfang Reservoir: The Underbog",
    "开启黑暗之门": "Black Morass",
    "地狱火堡垒：破碎大厅": "Hellfire Citadel: Shattered Halls",
    "盘牙湖泊：蒸汽地窟": "Coilfang Reservoir: The Steamvault",
    "地狱火堡垒：城墙": "Hellfire Citadel: The Ramparts",
    "风暴要塞：生态船": "Tempest Keep: The Botanica",
    "奥金顿：暗影迷宫": "Auchindoun: Shadow Labyrinth",
    "逃离敦霍尔德": "Old Hillsbrad Foothills",
    # ===== NATIVE 3.0 instances =====
    "乌特加德城堡": "Utgarde Keep",
    "魔环": "The Oculus",
    "萨隆矿坑": "Azjol-Nerub",
    "映像大厅": "Halls of Reflection",
    "古达克": "Gundrak",
    "冠军的试炼": "Trial of the Champion",
    "乌特加德之巅": "Utgarde Pinnacle",
    "闪电大厅": "Halls of Lightning",
    "岩石大厅": "Halls of Stone",
    "魔枢": "The Nexus",
    "达克萨隆要塞": "Drak'Tharon Keep",
    "紫罗兰监狱": "The Violet Hold",
    "艾卓-尼鲁布": "Ahn'kahet: The Old Kingdom",
    "灵魂洪炉": "Forge of Souls",
    "安卡赫特：古代王国": "Ahn'kahet: The Old Kingdom",
    # ===== NATIVE 4.0 instances =====
    "永恒之井": "Well of Eternity",
    "祖尔格拉布": "Zul'Gurub",
    "潮汐王座": "Throne of the Tides",
    "格瑞姆巴托": "Grim Batol",
    "黑石岩窟": "Blackrock Caverns",
    "巨石之核": "The Stonecore",
    "起源大厅": "Halls of Origination",
    "祖阿曼": "Zul'Aman",
    "暮光审判": "Hour of Twilight",
    "时光之末": "End Time",
    "旋云之巅": "Vortex Pinnacle",
    "托维尔失落之城": "Lost City of the Tol'vir",
    # ===== NATIVE 5.0 instances =====
    "围攻砮皂寺": "Siege of Niuzao Temple",
    "魔古山宫殿": "Mogu'shan Palace",
    "青龙寺": "Temple of the Jade Serpent",
    "影踪禅院": "Shado-Pan Monastery",
    "风暴烈酒酿造厂": "Stormstout Brewery",
    # ===== NATIVE 6.0 instances =====
    "黑石塔上层": "Upper Blackrock Spire",
    "奥金顿": "Auchindoun",
    "恐轨车站": "Iron Docks",
    "通天峰": "Skyreach",
    "影月墓地": "Shadowmoon Burial Grounds",
    "钢铁码头": "Grimrail Depot",
    "血槌炉渣矿井": "Bloodmaul Slag Mines",
    "永茂林地": "The Everbloom",
    # ===== NATIVE 7.0 instances =====
    "艾萨拉之眼": "Eye of Azshara",
    "群星庭院": "Court of Stars",
    "重返卡拉赞": "Return to Karazhan",
    "永夜大教堂": "Cathedral of Eternal Night",
    "守望者地窟": "Vault of the Wardens",
    "魔法回廊": "The Arcway",
    "英灵殿": "Halls of Valor",
    "噬魂之喉": "Maw of Souls",
    "奈萨里奥的巢穴": "Neltharion's Lair",
    "黑心林地": "Darkheart Thicket",
    # ===== NATIVE 8.0 instances =====
    "阿塔达萨": "Atal'Dazar",
    "风暴神殿": "Shrine of the Storm",
    "围攻伯拉勒斯": "Siege of Boralus",
    "托尔达戈": "Tol Dagor",
    "塞塔里斯神庙": "Temple of Sethraliss",
    "暴富矿区！！": "The MOTHERLODE!!",
    "自由镇": "Freehold",
    "维克雷斯庄园": "Waycrest Manor",
    "诸王之眠": "Kings' Rest",
    # ===== NATIVE 9.0 instances =====
    "彼界": "The Necrotic Wake",
    "塞兹仙林的迷雾": "Mists of Tirna Scithe",
    "赎罪大厅": "Halls of Atonement",
    "赤红深渊": "Sanguine Depths",
    "晋升高塔": "Spires of Ascension",
    "伤逝剧场": "Theater of Pain",
    "凋魂之殇": "Plaguefall",
    "通灵战潮": "Halls of Repose",
    # ===== NATIVE 10.0 instances =====
    "奥达曼：提尔的遗产": "Uldaman: Legacy of Tyr",
    "永恒黎明": "Dawn of the Infinite",
    "奈萨鲁斯": "Neltharus",
    "诺库德阻击战": "The Nokhud Offensive",
    "碧蓝魔馆": "The Azure Vault",
    "蕨皮山谷": "Brackenhide Hollow",
    "注能大厅": "Halls of Infusion",
    "红玉新生法池": "Ruby Life Pools",
    # ===== NATIVE 11.0 instances =====
    "圣焰隐修院": "Priory of the Sacred Flame",
    "燧酿酒庄": "Cinderbrew Meadery",
    "艾拉-卡拉，回响之城": "Ara-Kara, City of Echoes",
    "水闸行动": "Operation: Floodgate",
    "暗焰裂口": "Darkflame Cleft",
    "千丝之城": "City of Threads",
    "驭雷栖巢": "The Rookery",
    "矶石宝库": "The Stonevault",
    "破晨号": "The Dawnbreaker",
    # ===== NATIVE 12.0 instances =====
    "虚空之痕竞技场": "Voidscar Arena",
    "纳洛拉克的洞穴": "Nalorakk's Den",
    "毒牙祭坛": "Venomfang Altar",
    "密谋小径": "Plotshear Path",
    "夺目谷": "Dazzling Valley",
    # ===== RAID instances =====
    "奥妮克希亚的巢穴": "Onyxia's Lair",
    "安其拉神殿": "Ahn'Qiraj Temple",
    "祖尔格拉布": "Zul'Gurub",
    "安其拉废墟": "Ruins of Ahn'Qiraj",
    "黑翼之巢": "Blackwing Lair",
    "熔火之心": "Molten Core",
    "纳克萨玛斯": "Naxxramas",
    "太阳之井高地": "Sunwell Plateau",
    "海加尔山之战": "Battle for Mount Hyjal",
    "黑暗神殿": "Black Temple",
    "风暴要塞": "Tempest Keep",
    "毒蛇神殿": "Serpentshrine Cavern",
    "卡拉赞": "Karazhan",
    "十字军的试炼": "Trial of the Crusader",
    "冰冠堡垒": "Icecrown Citadel",
    "奥杜尔": "Ulduar",
    "红玉圣殿": "Ruby Sanctum",
    "巨龙之魂": "Dragon Soul",
    "暮光堡垒": "Bastion of Twilight",
    "火焰之地": "Firelands",
    "黑翼血环": "Blackwing Descent",
    "风神王座": "Throne of the Four Winds",
    "决战奥格瑞玛": "Siege of Orgrimmar",
    "恐惧之心": "Heart of Fear",
    "魔古山宝库": "Mogu'shan Vaults",
    "雷霆王座": "Throne of Thunder",
    "永春台": "Terrace of Endless Spring",
    "地狱火堡垒": "Hellfire Citadel",
    "悬锤堡": "Highmaul",
    "黑石铸造厂": "Blackrock Foundry",
    "勇气试炼": "Trial of Valor",
    "暗夜要塞": "The Nighthold",
    "安托鲁斯，燃烧王座": "Antorus, the Burning Throne",
    "翡翠梦魇": "The Emerald Nightmare",
    "萨格拉斯之墓": "Tomb of Sargeras",
    "奥迪尔": "Uldir",
    "达萨罗之战": "Battle of Dazar'alor",
    "永恒王宫": "Eternal Palace",
    "风暴熔炉": "Crucible of Storms",
    "尼奥罗萨，觉醒之城": "Ny'alotha, the Waking City",
    "统御圣所": "Sanctum of Domination",
    "初诞者圣墓": "Sepulcher of the First Ones",
    "纳斯利亚堡": "Castle Nathria",
    "亚贝鲁斯，焰影熔炉": "Aberrus, the Shadowed Crucible",
    "阿梅达希尔，梦境之愿": "Amirdrassil, the Dream's Hope",
    "化身巨龙牢窟": "Vault of the Incarnates",
    "法力熔炉：欧米伽": "Manaforge: Omega",
    "解放安德麦": "Liberation of Undermine",
    "尼鲁巴尔王宫": "Palace of Nerub'ar",
    "进军奎尔萨拉斯": "March on Quel'Thalas",
    "虚影尖塔": "Phantasmal Spire",
    "孢陨幽境": "Sporefall Sanctum",
    "梦境裂隙": "Dreamrift",
    "潮缚石窟": "Tidebound Grotto",
    "烈毒之渊": "The Venomous Abyss",

    # ===== v1.0 native boss names =====
    "猎手布塔斯克": "Huntmaster Buth'gul",
    "鲁古格": "Ruggl",
    "督军拉姆塔斯": "Warlord Ramtus",
    "盲眼猎手格罗亚特": "Blind Hunter Groth",
    "卡尔加·刺肋": "Kalgar Spinerend",
    "野猪人萨满": "Quilboar Shaman",
    "阿鲁克斯": "Arux",
    "火眼莫德雷斯": "Mordresh Fire Eye",
    "麦什伦": "Mesmlen",
    "亡语者布莱克松": "Death Speaker Blackhorn",
    "寒冰之王亚门纳尔": "King Aremnal the Frostborn",
    "野猪人狂战士": "Quilboar Berserker",
    "特迪斯·扭木": "Tendris Warpwood",
    "伊琳娜·暗木": "Illyanna Ravenoak",
    "卡雷迪斯镇长": "Councilman Kreedis",
    "伊莫塔尔": "Immol'thar",
    "托塞德林王子": "Prince Tortheldrin",
    "戈多克食人魔": "Gordok Ogre",
    "克雷什": "Kresh",
    "安娜科德拉": "Ana'kendra",
    "考布莱恩": "Cobblecrank",
    "皮萨斯": "Pythas",
    "斯卡姆": "Skum",
    "瑟芬迪斯": "Serpentis",
    "永生者沃尔丹": "Lord Vyletongue",
    "吞噬者穆坦努斯": "Mutanus the Devourer",
    "尖牙德鲁伊": "Serpentlord Druid",
    "鲁维罗什": "Rokgahr",
    "失落的矮人": "Lost Dwarves",
    "艾隆纳亚": "Ironaya",
    "黑曜石哨兵": "Obsidian Sentinel",
    "远古巨石卫士": "Ancient Stone Warden",
    "加加恩·火锤": "Gargok Firehammer",
    "格瑞姆洛克": "Grimlok",
    "阿扎达斯": "Archbishop",
    "黑铁矮人": "Dark Iron Dwarf",
    "灰葬男爵": "Baron Silverash",
    "席瓦莱恩男爵": "Baron Silverlaine",
    "指挥官斯普林瓦尔": "Commander Springvale",
    "沃登勋爵": "Lord Walden",
    "高弗雷勋爵": "Lord Godfrey",
    "影牙月行者": "Shadowy Moonwalker",
    "阿达罗格": "Adarogg",
    "黑暗萨满柯兰萨": "Dark Shaman Korlath",
    "焰喉": "Flamefang",
    "熔岩守卫戈多斯": "Lava Guard Gordoth",
    "弗雷斯特恩": "Frasteln",
    "不可宽恕者": "The Unforgiven",
    "邮差马龙": "Postmaster Malone",
    "残忍的提米": "Cruel Timmy",
    "指挥官玛洛尔": "Commander Mar'al",
    "希望破坏者威利": "Willy the Hopebreaker",
    "档案管理员加尔福特": "Archivist Galford",
    "巴纳扎尔": "Balnazzar",
    "血色巫术师": "Scarlet Warlock",
    "兰多菲·摩洛克": "Randolph Moloch",
    "灼热勋爵": "Lord Incendius",
    "霍格": "Hogger",
    "格拉布托克": "Glubtok",
    "赫利克斯·破甲": "Helix Gearbreaker",
    "死神5000": "Reaper 5000",
    "撕心狼将军": "General Umbriss",
    "\"船长\"曲奇": "Cookie",
    "梵妮莎·范克里夫": "Vanessa VanCleef",
    "哈卡的化身": "Avatar of Hakkar",
    "预言者迦玛兰": "Prophecy of Gamalan",
    "梦境守望者": "Dreamwatcher",
    "伊兰尼库斯的阴影": "Shade of Eranikus",
    "龙人": "Dragonspawn",
    "诺克赛恩": "Noxxion",
    "锐刺鞭笞者": "Razorlash",
    "工匠吉兹洛克": "Gizlock",
    "维利塔恩": "Vilennthar",
    "被诅咒的塞雷布拉斯": "Cursed Centbrass",
    "兰斯利德": "Landslide",
    "洛特格里普": "Lorgresh",
    "瑟莱德丝公主": "Princess Theradras",
    "瑟莱德丝卫士": "Theradras Guardian",
    "殉教者塞卡": "Martyr Seka",
    "安图苏尔": "Antu'sul",
    "水占师维蕾萨": "Water Diviner Vilesa",
    "巫医祖穆拉恩": "Witch Doctor Zum'rah",
    "加兹瑞拉": "Gahz'rilla",
    "耐克鲁姆和塞瑟斯": "Nekrum and Seresth",
    "乌克兹·沙顶": "Ukuz Sandtop",
    "沙怒暗影猎手": "Sandfury Shadowhunter",
    "裂魂者萨尔诺斯": "Soulflayer Salnus",
    "科洛夫修士": "Brother Korloff",
    "大检察官怀特迈恩": "High Inquisitor Whitemane",
    "血色招魂师": "Scarlet Necromancer",
    "驯犬者布兰恩": "Houndmaster Braun",
    "武器大师哈兰": "Weaponsmaster Halan",
    "织焰者孔格勒": "Flameweaver Kangle",
    "格鲁比斯": "Grobulus",
    "粘性辐射尘": "Viscous Fallout",
    "电刑器6000型": "Electrocutioner 6000",
    "群体打击者9-60": "Crowd Pummeler 9-60",
    "机械师瑟玛普拉格": "Mekgineer Thermaplugg",
    "自爆机器人": "Self-Destructing Robot",
    "指导者寒心": "Instructor Chillheart",
    "詹迪斯·巴罗夫": "Jandice Barov",
    "血骨傀儡": "Blood Bone Golem",
    "莉莉安·沃斯": "Lilian Voss",
    "黑暗院长加丁": "Darkmaster Gandling",
    "通灵法师": "Necromancer",
    "加摩拉": "Ghamoo-ra",
    "多米尼娜": "Dominina",
    "征服者克鲁尔": "Conqueror Krule",
    "苏克": "Suuk",
    "深渊守护者": "Abyssal Guardian",
    "刽子手戈尔": "Executioner Gore",
    "暮光领主巴赛尔": "Twilight Lord Bassei",
    "阿库麦尔": "Akumal",
    "暮光之锤祭司": "Twilight Hammer Priest",
    "欧莫克大王": "Warchief Omok",
    "暗影猎手沃什加斯": "Shadow Hunter Vosh'gajin",
    "指挥官沃恩": "Commander Wrenn",
    "烟网蛛后": "Smolderweb Matron",
    "尤洛克·暗嚎": "Urok Doomhowl",
    "军需官兹格雷斯": "Quartermaster Zigris",
    "哈雷肯": "Halycon",
    "奴役者基兹鲁尔": "Skullsplitter Kizrul",
    "维姆萨拉克": "Vermsakk",
    "黑手兽人": "Blackhand Orc",
    "审讯官格斯塔恩": "Inquisitor Ghestarn",
    "洛考尔": "Lokhlol",
    "驯犬者格雷布玛尔": "Houndmaster Grebmar",
    "秩序竞技场": "Arena of Order",
    "控火师罗格雷恩": "Pyromancer Loregrain",
    "伊森迪奥斯": "Isendir",
    "典狱官斯迪尔基斯": "Warden Stilgiss",
    "弗诺斯·达克维尔": "Fineous Darkvire",
    "贝尔加": "Bergall",
    "怒炉将军": "General Angerforge",
    "傀儡统帅阿格曼奇": "Puppetmaster Agmanchi",
    "霍尔雷·黑须": "Hurley Blackbeard",
    "法拉克斯": "Phalanx",
    "普拉格": "Plugger Spazzring",
    "弗莱拉斯总大使": "Ambassador Flamelash",
    "黑铁七贤": "Seven Dwarves",
    "玛格姆斯": "Magmus",
    "达格兰·索瑞森大帝": "Emperor Dagran Thaurissan",
}

TIP_MAP = {
    # ===== 剃刀沼泽 =====
    ("猎手布塔斯克", "lfr"): '{rt8}Huntmaster Buth\'gul{rt8}||[Quick Shot] chains the target; avoid [Flame Arrow Rain] at its landing spot; at half health [Boar Charge] summons stompers—spread out.||{rt1}Must interrupt: none{rt1}||Tank steady; dodge the charge at half health.',
    ("鲁古格", "lfr"): '{rt8}Ruggl{rt8}||[Lightning Bolt]; [Healing Wave] must be interrupted; [Poison] is a DoT.||{rt1}Must interrupt: Healing Wave{rt1}||Clear summons quickly.',
    ("督军拉姆塔斯", "lfr"): '{rt8}Warlord Ramtus{rt8}||[Cleave]/[Enrage]; tank faces it away from the wall.||{rt1}Must interrupt: none{rt1}||',
    ("盲眼猎手格罗亚特", "lfr"): '{rt8}Blind Hunter Groth{rt8}||[Shadow Bolt]/[Dive]; tank holds it.||{rt1}Must interrupt: Shadow Bolt{rt1}||',
    ("卡尔加·刺肋", "lfr"): '{rt8}Kalgar Spinerend{rt8}||[Chain Lightning]/[Purify] is immune/[Renew]—interrupt Renew.||{rt1}Must interrupt: Renew{rt1}||Spread to dodge the chain.',
    ("野猪人萨满", "mob"): '{rt8}Priority: Quilboar Shaman{rt8}||[Chain Lightning] must be interrupted; prioritize control-kill.||{rt1}Must interrupt: Chain Lightning{rt1}||',
    # ===== 剃刀高地 =====
    ("阿鲁克斯", "lfr"): '{rt8}Arux{rt8}||[Web] pulls people close; [Bursting Boil] poison burst; [Plague Bite] is a disease.||{rt1}Must interrupt: none{rt1}||Run out of webs; dispel the disease.',
    ("火眼莫德雷斯", "lfr"): '{rt8}Mordresh Fire Eye{rt8}||[Lava Burst] fire damage on target; [Summon Blazing Servant] clear the servant; [Flame Link] beam contact drains HP—avoid.||{rt1}Must interrupt: Fire spells{rt1}||Spread and avoid the link.',
    ("麦什伦", "lfr"): '{rt8}Mesmlen{rt8}||[Nauseous] long cone—avoid; [Putrid Stench] poison pool at feet—avoid; [Smack] triple hit—tank faces it.||{rt1}Must interrupt: none{rt1}||Keep moving.',
    ("亡语者布莱克松", "lfr"): '{rt8}Death Speaker Blackhorn{rt8}||[Shadow Bolt]/[Heal] interrupt heals; after adjutants die he [Revives Adjutant]—kill fast.||{rt1}Must interrupt: Heal{rt1}||Clear the three adjutants first, then the boss.',
    ("寒冰之王亚门纳尔", "lfr"): '{rt8}King Aremnal the Frostborn{rt8}||[Frostbolt] slows; [Frost Nova] roots—avoid; [Aremnal\'s Wrath] knockback; [Frost Armor] slows attack speed; [Summon Ice Wraith] ignore.||{rt1}Must interrupt: Frost{rt1}||Kill and take the head.',
    ("野猪人狂战士", "mob"): '{rt8}Priority: Quilboar Berserker{rt8}||[Enrage] at low health; control priority.||{rt1}Must interrupt: none{rt1}||',
    # ===== 厄运之槌 =====
    ("特迪斯·扭木", "lfr"): '{rt8}Tendris Warpwood{rt8}||[Entangle] roots; [Captured Vines]/[Stomp]—ranged/cloth stay away from dispellable.||{rt1}Must interrupt: none{rt1}||',
    ("伊琳娜·暗木", "lfr"): '{rt8}Illyanna Ravenoak{rt8}||[Multi-Shot]/[Volley] avoid dead zone; [Immolation Trap]; [Concussive Shot]; bear [Charge]/[Cleave]—kill the bear first.||{rt1}Must interrupt: none{rt1}||Stand in the dead zone.',
    ("卡雷迪斯镇长", "lfr"): '{rt8}Councilman Kreedis{rt8}||[Shadow Bolt] interrupt; [Disarm] drops weapon; [Arcane Amplification] increases damage; [Summon].||{rt1}Must interrupt: Shadow Bolt{rt1}||Use ranged/spells when disarmed.',
    ("伊莫塔尔", "lfr"): '{rt8}Immol\'thar{rt8}||[Corrosive Bite] nature DoT; [Enrage] attack speed up; [Stomp]; [Teleport] clears threat; [Summon Eye] slows.||{rt1}Must interrupt: none{rt1}||Prioritize killing the eyes.',
    ("托塞德林王子", "lfr"): '{rt8}Prince Tortheldrin{rt8}||[Arcane Blast] knockback; [Flurry] AoE; [Spell Reflection] interrupts; break the ward first.||{rt1}Must interrupt: Arcane{rt1}||Break the shield then focus fire.',
    ("戈多克食人魔", "mob"): '{rt8}Priority: Gordok Ogre{rt8}||High damage; prioritize control-kill.||{rt1}Must interrupt: none{rt1}||',
    # ===== 哀嚎洞穴 =====
    ("克雷什", "lfr"): '{rt8}Kresh{rt8}||Tank steady; drops tank shield.||{rt1}Must interrupt: none{rt1}||',
    ("安娜科德拉", "lfr"): '{rt8}Ana\'kendra{rt8}||[Sleep] must be interrupted; avoid spawning adds.||{rt1}Must interrupt: Sleep{rt1}||Focus the three snakes.',
    ("考布莱恩", "lfr"): '{rt8}Cobblecrank{rt8}||[Sleep]/snake form; interrupt Sleep.||{rt1}Must interrupt: Sleep{rt1}||',
    ("皮萨斯", "lfr"): '{rt8}Pythas{rt8}||[Sleep] interrupt; clear the add first.||{rt1}Must interrupt: Sleep{rt1}||',
    ("斯卡姆", "lfr"): '{rt8}Skum{rt8}||[Chain Lightning]—spread out.||{rt1}Must interrupt: none{rt1}||',
    ("瑟芬迪斯", "lfr"): '{rt8}Serpentis{rt8}||[Sleep] must be interrupted; disarms hunters.||{rt1}Must interrupt: Sleep{rt1}||',
    ("永生者沃尔丹", "lfr"): '{rt8}Lord Vyletongue{rt8}||[Entangling Vines] roots; ranged/healers stay away.||{rt1}Must interrupt: none{rt1}||',
    ("吞噬者穆坦努斯", "lfr"): '{rt8}Mutanus the Devourer{rt8}||melee AoE stun/[Fear]; ranged stay away to avoid fear.||{rt1}Must interrupt: none{rt1}||Kill once per run.',
    ("尖牙德鲁伊", "mob"): '{rt8}Priority: Serpentlord Druid{rt8}||[Sleep] must be interrupted; prioritize control-kill of casters.||{rt1}Must interrupt: Sleep{rt1}||',
    # ===== 奥达曼 =====
    ("鲁维罗什", "lfr"): '{rt8}Rokgahr{rt8}||[Chain Lightning]/[Lightning Shield]/[Stun]—spread and dodge the chain, clear summons.||{rt1}Must interrupt: none{rt1}||',
    ("失落的矮人", "lfr"): '{rt8}Lost Dwarves{rt8}||3 dwarves up with [Enrage]/[Stun]; control then focus fire.||{rt1}Must interrupt: none{rt1}||',
    ("艾隆纳亚", "lfr"): '{rt8}Ironaya{rt8}||[Cleave] front; [Knockback]; [War Stomp] AoE stun—spread.||{rt1}Must interrupt: none{rt1}||Gather keys to activate.',
    ("黑曜石哨兵", "lfr"): '{rt8}Obsidian Sentinel{rt8}||[Obsidian Reflection] 20% spell reflect—casters beware; [Shatter Obsidian] splits adds; each shatter lowers boss attack.||{rt1}Must interrupt: none{rt1}||Casters watch reflect; clear shards fast.',
    ("远古巨石卫士", "lfr"): '{rt8}Ancient Stone Warden{rt8}||[Sandstorm] movement slow; [City Defender] summons.||{rt1}Must interrupt: none{rt1}||Keep moving, clear adds.',
    ("加加恩·火锤", "lfr"): '{rt8}Gargok Firehammer{rt8}||[Flame Nova] melee stay away; [Flame Lash] fire + fire-resist debuff stacks; [Flame Amplitude] more fire damage; with [Darkforge Geologist] fire pillars—clear fast.||{rt1}Must interrupt: fire pillars{rt1}||Tank fire resist; clear the adds first.',
    ("格瑞姆洛克", "lfr"): '{rt8}Grimlok{rt8}||[Chain Lightning]/[Lightning Bolt] interrupt; [Bloodlust] speeds up adds; with [Stonewatcher] uses [Crystal Slumber] stun.||{rt1}Must interrupt: Lightning{rt1}||Clear slimes and basilisks.',
    ("阿扎达斯", "lfr"): '{rt8}Archbishop{rt8}||[Resurrect Dwarf]/[Petrify]/[Summon Stone]||{rt1}Must interrupt: none{rt1}||Prioritize revived dwarves; at 1/3 HP focus the boss.',
    ("黑铁矮人", "mob"): '{rt8}Priority: Dark Iron Dwarf{rt8}||caster high damage; prioritize control-kill.||{rt1}Must interrupt: Spell{rt1}||',
}
