# -*- coding: utf-8 -*-
# Raid boss name crosswalk: exact source Lua boss KEY (zh) -> en display name.
# For header-type bosses the value MUST equal the exact {rt8} header string
# used in _new_en.txt so gen_raid_en_v2.py can join the translated tip.
# For headless-type bosses the value is an accurate display name (tip is
# translated fresh and not joined from _new_en.txt).

RAID_BOSS_NAME_MAP = {
    # ===================== v1.0 安其拉废墟 (Ruins of Ahn'Qiraj) =====================
    "拉贾克斯将军": "General Rajaxx",
    "库林纳克斯": "Kurinaxx",
    "莫阿姆": "Moam",
    "狩猎者阿亚米斯": "Ayamiss the Hunter",
    "无疤者奥斯里安": "Ossirian the Unscarred",
    "吞咽者布鲁": "Buru the Gorger",
    # ===================== v1.0 黑翼之巢 (Blackwing Lair) =====================
    "奈法利安": "Nefarian",
    "克洛玛古斯": "Chromaggus",
    "弗莱格尔": "Flamegor",
    "勒什雷尔": "Broodlord Lashlayer",
    "埃博诺克": "Ebonroc",
    "狂野的拉佐格尔": "Razorgore the Untamed",
    "费尔默": "Firemaw",
    "堕落的瓦拉斯塔兹": "Vaelastrasz the Corrupt",
    # ===================== v1.0 奥妮克希亚的巢穴 (Onyxia's Lair) =====================
    "奥妮克希亚": "Onyxia",
    # ===================== v1.0 熔火之心 (Molten Core) =====================
    "迦顿男爵": "Baron Geddon",
    "鲁西弗隆": "Lucifron",
    "沙斯拉尔": "Shazzrah",
    "拉格纳罗斯": "Ragnaros",
    "基赫纳斯": "Gehennas",
    "玛格曼达": "Magmadar",
    "加尔": "Garr",
    "萨弗隆先驱者": "Sulfuron Harbinger",
    "焚化者古雷曼格": "Golemagg the Incinerator",
    "管理者埃克索图斯": "Majordomo Executus",
    "熔火核心": "Molten Core",
    # ===================== v1.0 祖尔格拉布 (Zul'Gurub) =====================
    "高阶祭司塞卡尔": "High Priest Sekar",
    "疯狂之缘": "Edge of Madness",
    "哈卡": "Hakkar",
    "高阶祭司耶克里克": "High Priestess Jeklik",
    "血领主曼多基尔": "Bloodlord Mandokir",
    "加兹兰卡": "Gahz'ranka",
    "高阶祭司玛尔里": "High Priestess Mar'li",
    "妖术师金度": "Jin'do the Hexxer",
    "高阶祭司阿洛克": "High Priest Thekal",
    "高阶祭司维诺克西斯": "High Priest Venoxis",
    # ===================== v1.0 安其拉神殿 (Ahn'Qiraj Temple) =====================
    "哈霍兰公主": "Princess Huhuran",
    "双子皇帝": "Twin Emperors",
    "维希度斯": "Viscidus",
    "预言者斯克拉姆": "Prophet Skeram",
    "沙尔图拉": "Sartura",
    "奥罗": "Ouro",
    "顽强的范克瑞斯": "Fankriss the Unyielding",
    "克苏恩": "C'Thun",
    "安其拉三宝": "AQ20 Trio",
    # ===================== v1.0 纳克萨玛斯 (Naxxramas) =====================
    "药剂师诺斯": "Apothecary Raz",
    "教官拉苏维奥斯": "Instructor Razuvious",
    "克尔苏加德": "Kel'Thuzad",
    "格罗布鲁斯": "Grobbulus",
    "迈克斯纳": "Maexxna",
    "肮脏的希尔盖": "Heigan the Unclean",
    "黑女巫法琳娜": "Black Witch Faline",
    "萨菲隆": "Sapphiron",
    "格拉斯": "Gluth",
    "塔迪乌斯": "Thaddius",
    "帕奇维克": "Patchwerk",
    "收割者戈提克": "Gothik the Harvester",
    "天启四骑士": "Four Horsemen",
    "阿努布雷坎": "Anub'Rekhan",
    "洛欧塞布": "Loatheb",
    # ===================== v2.0 祖阿曼 (Zul'Aman) =====================
    "加亚莱": "Jan'alai",
    "埃基尔松": "Akil'zon",
    "祖尔金": "Zul'jin",
    "妖术领主玛拉卡斯": "Hex Lord Malacrass",
    "哈尔拉兹": "Halazzi",
    "纳洛拉克": "Nalorakk",
    # ===================== v2.0 风暴要塞 (Tempest Keep) =====================
    "大星术师索兰莉安": "High Astromancer Solarian",
    "凯尔萨斯·逐日者": "Kael'thas Sunstrider",
    "奥": "Void Reaver",
    "空灵机甲": "Al'ar",
    # ===================== v2.0 太阳之井高地 (Sunwell Plateau) =====================
    "卡雷苟斯": "Kalecgos",
    "布鲁塔卢斯": "Brutallus",
    "菲米丝": "Felmyst",
    "穆鲁": "M'uru",
    "基尔加丹": "Kil'jaeden",
    "艾瑞达双子": "Eredar Twins",
    # ===================== v2.0 海加尔山之战 (Battle for Mount Hyjal) =====================
    "安纳塞隆": "Anetheron",
    "雷基·冬寒": "Rage Winterchill",
    "卡兹洛加": "Kaz'rogal",
    "阿兹加洛": "Azgalor",
    "阿克蒙德": "Archimonde",
    # ===================== v2.0 卡拉赞 (Karazhan) =====================
    "夜之魇": "Nightbane",
    "猎手阿图门": "Attumen the Huntsman",
    "大灰狼": "Big Bad Wolf",
    "虚空幽龙": "Netherspite",
    "罗密欧与朱丽叶": "Romeo and Juliet",
    "仆役宿舍": "The Servant's Quarters",
    "玛克扎尔王子": "Prince Malchezaar",
    "老巫婆": "The Crone",
    "特雷斯坦·邪蹄": "Terestian Illhoof",
    "莫罗斯": "Moroes",
    "埃兰之影": "Shade of Aran",
    "馆长": "The Curator",
    "贞节圣女": "Maiden of Virtue",
    # ===================== v2.0 毒蛇神殿 (Serpentshrine Cavern) =====================
    "鱼斯拉": "The Lurker Below",
    "盲眼者莱欧瑟拉斯": "Leotheras the Blind",
    "莫洛格里·踏潮者": "Morogrim Tidewalker",
    "瓦丝琪": "Lady Vashj",
    "不稳定的海度斯": "Hydross the Unstable",
    "深水领主卡拉瑟雷斯": "Fathom-Lord Karathress",
    # ===================== v2.0 黑暗神殿 (Black Temple) =====================
    "阿卡玛之影": "Akama's Shadow",
    "塔隆·血魔": "Teron Gorefiend",
    "苏普雷姆斯": "Supremus",
    "灵魂之匣": "Reliquary of Souls",
    "高阶督军纳因图斯": "High Warlord Naj'entus",
    "古尔图格·血沸": "Gurtogg Bloodboil",
    "伊利达雷议会": "Illidari Council",
    "莎赫拉丝主母": "Mother Shahraz",
    "伊利丹·怒风": "Illidan Stormrage",
    # ===================== v3.0 红玉圣殿 (Ruby Sanctum) =====================
    "海里昂": "Halion",
    # ===================== v3.0 冰冠堡垒 (Icecrown Citadel) =====================
    "烂肠": "Rotface",
    "亡语者女士": "Lady Deathwhisper",
    "普崔塞德教授": "Professor Putricide",
    "辛达苟萨": "Sindragosa",
    "踏梦者瓦莉瑟瑞娅": "Valithria Dreamwalker",
    "巫妖王": "The Lich King",
    "鲜血女王兰娜瑟尔": "Blood-Queen Lana'thel",
    "腐面": "Festergut",
    "死亡使者萨鲁法尔": "Deathbringer Saurfang",
    "鲜血王子议会": "Blood Prince Council",
    "玛洛加尔领主": "Lord Marrowgar",
    "冰冠冰川炮舰战": "Gunship Battle",
    # ===================== v3.0 十字军的试炼 (Trial of the Crusader) =====================
    "阿努巴拉克": "Anub'arak",
    "加拉克苏斯大王": "Lord Jaraxxus",
    "瓦格里双子": "The Val'kyr Twins",
    "部落的冠军": "The Champions",
    "诺森德猛兽": "Northrend Beasts",
    # ===================== v3.0 奥杜尔 (Ulduar) =====================
    "尤格-萨隆": "Yogg-Saron",
    "XT-002拆解者": "XT-002 Deconstructor",
    "霍迪尔": "Hodir",
    "米米尔隆": "Mimiron",
    "欧尔莉亚": "Auriaya",
    "科隆加恩": "Kologarn",
    "观察者奥尔加隆": "Algalon the Observer",
    "维扎克斯将军": "General Vezax",
    "钢铁议会": "Iron Council",
    "弗蕾亚": "Freya",
    "烈焰巨兽": "Flame Leviathan",
    "掌炉者伊格尼斯": "Ignis the Furnace Master",
    "锋鳞": "Razorscale",
    "托里姆": "Thorim",
    # ===================== v3.0 纳克萨玛斯 (Naxxramas, WotLK) =====================
    "药剂师诺斯": "Apothecary Raz",
    "教官拉苏维奥斯": "Instructor Razuvious",
    "克尔苏加德": "Kel'Thuzad",
    "格罗布鲁斯": "Grobbulus",
    "迈克斯纳": "Maexxna",
    "肮脏的希尔盖": "Heigan the Unclean",
    "黑女巫法琳娜": "Black Witch Faline",
    "萨菲隆": "Sapphiron",
    "格拉斯": "Gluth",
    "塔迪乌斯": "Thaddius",
    "帕奇维克": "Patchwerk",
    "收割者戈提克": "Gothik the Harvester",
    "天启四骑士": "Four Horsemen",
    "阿努布雷坎": "Anub'Rekhan",
    "洛欧塞布": "Loatheb",
    # ===================== v4.0 风神王座 (Throne of the Four Winds) =====================
    "奥拉基尔": "Al'Akir",
    "风之议会": "Conclave of Wind",
    # ===================== v4.0 黑翼血环 (Blackwing Descent) =====================
    "玛洛拉克": "Malorak",
    "奈法利安": "Nefarian",
    "奇美隆": "Chimaeron",
    "欧姆诺顿防御系统": "Omnotron Defense System",
    "阿特拉米德": "Atramedes",
    "玛格玛尔": "Magmaw",
    # ===================== v4.0 巨龙之魂 (Dragon Soul) =====================
    "死亡之翼的疯狂": "The Madness of Deathwing",
    "死亡之翼的脊背": "The Spine of Deathwing",
    "莫卓克": "Morchok",
    "督军佐诺兹": "Warlord Zon'ozz",
    "黑角": "Blackhorn",
    "哈加拉·风暴绑缚者": "Hagara the Stormbinder",
    "奥特拉希昂": "Yor'sahj the Unsleeping",
    "不眠的约沙伊": "Ultraxion",
    # ===================== v4.0 暮光堡垒 (Bastion of Twilight) =====================
    "古加尔": "Cho'gall",
    "瓦里奥娜与瑟拉利昂": "Valiona and Theralion",
    "晋升者议会": "Council of Exarchs",
    "哈尔弗斯·碎龙者": "Halfus Wyrmbreaker",
    "辛奈丝特拉": "Sinestra",
    # ===================== v4.0 火焰之地 (Firelands) =====================
    "贝丝蒂拉克": "Beth'tilac",
    "奥利瑟拉佐尔": "Alysrazor",
    "拉格纳罗斯": "Ragnaros",
    "沙诺克斯": "Shannox",
    "莱诺斯领主": "Lord Rhyolith",
    "巴拉克雷斯": "Baleroc",
    "大管家斯塔格海尔": "Fandral Staghelm",
    # ===================== v5.0 雷霆王座 (Throne of Thunder) =====================
    "普利莫求斯": "Primordius",
    "铁库昂": "Iron Qon",
    "雷神": "Lei Shen",
    "遗忘者杜鲁姆": "Durumu the Forgotten",
    "雷登": "Ra-den",
    "托托斯": "Tortos",
    "长者议会": "The Spirit Kings",
    "黑暗活化体": "Dark Animus",
    "美拉盖拉": "Megaera",
    "霍利顿": "Horridon",
    "双后": "The Twin Consorts",
    "吉库恩": "Ji-Kun",
    "破坏者金罗克": "Jin'rokh the Breaker",
    # ===================== v5.0 恐惧之心 (Heart of Fear) =====================
    "加拉隆": "Garalon",
    "女皇谢兹卡尔": "Empress Shek'zeer",
    "剑圣塔亚克": "Blade Lord Ta'yak",
    "帝国宰相佐拉洛克": "Imperial Vizier Zor'lok",
    "琥珀塑形者昂绍克": "Amber-Shaper Un'sok",
    "风领主梅尔加拉克": "Wind Lord Mel'jarak",
    # ===================== v5.0 魔古山宝库 (Mogu'shan Vaults) =====================
    "皇帝的意志": "The Emperor's Will",
    "伊拉贡": "Elegon",
    "灵魂王": "The Spirit Kings",
    "石头守卫": "The Stone Guard",
    "受诅者冯": "Feng the Accursed",
    "缚灵者戈拉亚": "Gara'jal the Spiritbinder",
    # ===================== v5.0 永春台 (Terrace of Endless Spring) =====================
    "烛龙": "Tsulong",
    "无尽者守护者": "Protectors of the Endless",
    "惧之煞": "Sha of Fear",
    "雷施": "Lei Shi",
    # ===================== v5.0 决战奥格瑞玛 (Siege of Orgrimmar) =====================
    "螳螂妖英杰": "The Klaxxi Paragons",
    "加尔鲁什·地狱咆哮": "Garrosh Hellscream",
    "嗜血的索克": "Thok the Bloodthirsty",
    "伊墨苏斯": "Immerseus",
    "潘达利亚的战利品": "The Pandaria Treasure",
    "堕落的守护者": "The Fallen Protectors",
    "纳兹戈林将军": "General Nazgrim",
    "攻城师黑弗斯": "Siegecrafter Blackfuse",
    "迦拉卡斯": "Galakras",
    "马尔考洛克": "Malkorok",
    "库卡隆黑暗萨满": "Kor'kron Dark Shaman",
    "傲之煞": "Sha of Pride",
    "钢铁战神": "Iron Juggernaut",
    "诺鲁什": "Norushen",
    # ===================== v6.0 地狱火堡垒 (Hellfire Citadel) =====================
    "暗影领主伊斯卡尔": "Shadow-Lord Iskar",
    "邪能领主扎库恩": "Fel Lord Zakuun",
    "戈尔菲恩德": "Gorefiend",
    "基尔罗格·死眼": "Kilrogg Deadeye",
    "钢铁劫掠者": "Iron Reaver",
    "地狱火高阶议会": "Hellfire High Council",
    "祖尔霍拉克": "Hellfire Assault",
    "玛诺洛斯": "Mannoroth",
    "阿克蒙德": "Archimonde",
    "永恒者索克雷萨": "Sorceras the Eternal",
    "地狱火突袭": "Hellfire Assault",
    "科尔莫克": "Kormrok",
    "暴君维哈里": "Tyrant Velhari",
    # ===================== v6.0 黑石铸造厂 (Blackrock Foundry) =====================
    "黑手": "Blackhand",
    "钢铁女武神": "The Iron Maidens",
    "奥雷戈格": "Oregorger",
    "熔炉": "The Blast Furnace",
    "索加尔": "Kromog",
    "克罗莫格": "Kromog",
    "格鲁尔": "Gruul",
    "汉斯加尔与弗兰佐克": "Hans'gar and Franzok",
    "兽王达玛拉克": "Beastlord Darmac",
    "烈焰编织者卡格拉兹": "Flamebender Ka'graz",
    # ===================== v6.0 悬锤堡 (Highmaul) =====================
    "元首马尔高克": "Imperator Mar'gok",
    "双子奥格隆": "Twin Ogron",
    "泰克图斯": "Tectus",
    "布雷肯斯波雷": "Brackenspore",
    "卡加斯·刃拳": "Kargath Bladefist",
    "科拉格": "Ko'ragh",
    "屠夫": "The Butcher",
    # ===================== v7.0 萨格拉斯之墓 (Tomb of Sargeras) =====================
    "戈罗斯": "Goroth",
    "捶击者哈加坦": "Harjatan",
    "萨丝丝女士": "Lady Sassz'ine",
    "月之姐妹": "Sisters of the Moon",
    "恶魔审判庭": "Demonic Inquisition",
    "基尔加丹": "Kil'jaeden",
    "守夜圣女": "Grand Magistrix Elisande",
    "荒寂之主": "The Desolate Host",
    "堕落化身": "Fallen Avatar",
    # ===================== v7.0 勇气试炼 (Trial of Valor) =====================
    "海拉": "Helya",
    "古尔姆": "Guarm",
    "奥丁": "Odyn",
    # ===================== v7.0 安托鲁斯，燃烧王座 (Antorus, the Burning Throne) =====================
    "生命缚誓者艾欧娜尔": "Eonar the Life-Binder",
    "萨格拉斯的邪犬": "The Felhounds of Sargeras",
    "金加罗斯": "Kin'garoth",
    "猎魂者伊莫纳尔": "Imonar the Soulhunter",
    "瓦里玛萨斯": "Varimathras",
    "传送门守护者哈西贝尔": "Portal Keeper Hasabel",
    "寂灭者阿古斯": "Argus the Unmaker",
    "希瓦尔拉议会": "The Coven of Shivarra",
    "安托兰高阶指挥官": "Antoran High Command",
    "戈罗提碎界者": "Garothi Worldbreaker",
    "阿格拉玛": "Aggramar",
    # ===================== v7.0 暗夜要塞 (Nighthold) =====================
    "斯考匹隆": "Skorpyron",
    "星界预言者埃特柔斯": "Star Augur Etraeus",
    "高阶植物学家特尔安": "High Botanist Tel'arn",
    "古尔丹": "Gul'dan",
    "崔里阿克丝": "Trilliax",
    "咒剑士奥鲁瑞尔": "Spellblade Aluriel",
    "克洛苏斯": "Krosus",
    "提克迪奥斯": "Tichondrius",
    "时空畸体": "Temporal Anomaly",
    "大魔导师艾莉桑德": "Grand Magistrix Elisande",
    # ===================== v7.0 翡翠梦魇 (Emerald Nightmare) =====================
    "伊格诺斯": "Il'gynoth",
    "塞纳留斯": "Cenarius",
    "乌索克": "Ursoc",
    "梦魇之龙": "Dragons of Nightmare",
    "艾勒瑞瑟·衰亡者": "Elerethe Renferal",
    "萨维斯": "Xavius",
    "尼珊德拉": "Nythendra",
    # ===================== v8.0 达萨罗之战 (Battle of Dazar'alor) =====================
    "玉火大师·联盟": "Jade Fire Master (Alliance)",
    "圣光勇士·联盟": "Lightforged Crusader (Alliance)",
    "玉火大师·部落": "Jade Fire Master (Horde)",
    "格隆·部落": "Grong (Horde)",
    "格隆·联盟": "Grong (Alliance)",
    "圣光勇士·部落": "Lightforged Crusader (Horde)",
    "被选者议会": "Council of the Chosen",
    "吉安娜·普罗德摩尔": "Jaina Proudmoore",
    "奥波伦斯": "Opulence",
    "风暴墙封锁": "Stormwall Blockade",
    "大工匠梅卡托克": "High Tinker Mekkatorque",
    "拉斯塔哈大王": "King Rastakhan",
    # ===================== v8.0 尼奥罗萨，觉醒之城 (Ny'alotha, the Waking City) =====================
    "伊格诺斯·重生腐蚀": "Il'gynoth, Corruption Reborn",
    "玛乌特": "Maut",
    "拉希奥": "Rashio",
    "先知斯吉特拉": "Prophet Skitra",
    "恩佐斯之壳": "The Carapace of N'Zoth",
    "蜂巢意识": "The Hivemind",
    "黑暗审判官萨尼什": "Dark Inquisitor Sanish",
    "恩佐斯·腐蚀者": "N'Zoth the Corruptor",
    "德雷斯塔加斯": "Drest'agath",
    "维克西奥娜": "Vexiona",
    "被亵渎的雷登": "Ra-den the Despoiled",
    "永渴的沙德哈": "Shad'har the Insatiable",
    # ===================== v8.0 风暴熔炉 (Crucible of Storms) =====================
    "乌纳特·虚空先驱": "Un'at the Void Herald",
    "不宁的卡巴尔": "The Restless Cabal",
    # ===================== v8.0 永恒王宫 (Eternal Palace) =====================
    "深渊指挥官希瓦拉": "Abyssal Commander Sivara",
    "黑水巨兽": "Blackwater Behemoth",
    "阿什凡女士": "Lady Ashvane",
    "女王之庭": "The Queen's Court",
    "扎库尔·尼奥罗萨先驱": "Za'qul",
    "艾萨拉之辉": "Radiance of Azshara",
    "艾萨拉女王": "Queen Azshara",
    "奥戈佐亚": "Ogozoa",
    # ===================== v8.0 奥迪尔 (Uldir) =====================
    "泽克沃兹·恩佐斯先驱": "Zek'voz, Herald of N'Zoth",
    "祖尔": "Zul",
    "解构者米斯拉克斯": "Mislax the Deconstructor",
    "母体": "The Mother",
    "维克提斯": "Vectis",
    "塔洛克": "Taloc",
    "腐臭吞噬者": "Fetid Devourer",
    "格胡恩": "G'huun",
    # ===================== v9.0 纳斯利亚堡 (Castle Nathria) =====================
    "石卫军将领": "Stone Legion Generals",
    "饥渴毁灭者": "Hungering Destroyer",
    "狩猎者阿尔提莫": "Huntsman Altimor",
    "工匠佐莫克斯": "Artificer Xy'mox",
    "尖啸翼": "Shriekwing",
    "太阳王救赎": "Sun King's Salvation",
    "泥拳": "Sludgefist",
    "血誓议会": "The Council of Blood",
    "伊涅瓦·暗脉女士": "Inerva Darkvein",
    "德纳修斯大帝": "Sire Denathrius",
    # ===================== v9.0 初诞者圣墓 (Sepulcher of the First Ones) =====================
    "恐惧领主": "Lords of Dread",
    "安度因·乌瑞恩": "Anduin Wrynn",
    "回收者哈拉顿": "Halondrus the Reclaimer",
    "堕落先知道塞格涅": "Dausegne the Fallen Oracle",
    "守夜卫士": "Vigilant Guardian",
    "莱盖隆": "Rygelon",
    "万神殿原型": "Pantheon Prototype",
    "工匠佐莫克斯·再临": "Artificer Xy'mox (return)",
    "首席建筑师利胡维姆": "Chief Architect Li'huveim",
    "典狱长": "The Jailer",
    "贪食吞噬者斯科莱克斯": "Skolex the Insatiable Devourer",
    # ===================== v9.0 统御圣所 (Sanctum of Domination) =====================
    "希尔瓦娜斯·风行者": "Sylvanas Windrunner",
    "典狱长之眼": "Eye of the Jailer",
    "塔拉格鲁": "The Tarragrue",
    "九人议会": "The Nine",
    "裂魂者多玛赞": "Soulrender Dormazain",
    "克尔苏加德": "Kel'Thuzad",
    "命运抄写者罗-卡洛": "Fatescribe Roh-Kalo",
    "初诞者卫士": "Vigilant Warden",
    "耐奥祖残魂": "Remnant of Ner'zhul",
    "痛苦工匠拉兹纳尔": "Painsmith Raznal",
    # ===================== v10.0 亚贝鲁斯，焰影熔炉 (Aberrus, the Shadowed Crucible) =====================
    "鳞长萨卡雷斯": "Scalecommander Sarkareth",
    "警戒管家兹斯卡尔恩": "The Vigilant Steward Zskarn",
    "玛格莫拉克": "Magmorax",
    "地狱熔铸卡扎拉": "Kazzara the Hellforged",
    "扎卡利突袭": "Assault of the Zaqali",
    "长者拉肖克": "Rashok the Elder",
    "耐萨里奥回响": "Echo of Neltharion",
    "融合密室": "Fusion Chamber",
    "被遗忘的实验": "The Forgotten Experiments",
    # ===================== v10.0 化身巨龙牢窟 (Vault of the Incarnates) =====================
    "库罗格·恐图腾": "Kurog Grimtotem",
    "飞升的达西娅": "Broodkeeper Diurna",
    "埃拉诺格": "Eranog",
    "泰罗斯": "Terros",
    "寒息森纳丝": "Sennarth the Cold Breath",
    "原始议会": "The Primal Council",
    "噬雷者拉兹加斯": "Raszageth the Storm-Eater",
    "孵雏者迪乌娜": "Dathea Ascended",
    # ===================== v10.0 阿梅达希尔，梦境之愿 (Amirdrassil, the Dream's Hope) =====================
    "火焰守护者拉罗达尔": "Larodar, Keeper of the Flame",
    "炽燃菲拉克斯": "Smolderon",
    "残酷的伊吉拉": "Igira the Cruel",
    "轮回编织者尼缪": "Nymue, Weaver of the Cycle",
    "梦境议会": "Dream Council",
    "纠结根须": "Gnarlroot",
    "火焰先知廷德拉尔": "Tindral Sageswift",
    "沃尔科罗斯": "Volcoross",
    "斯莫德隆": "Fyrakk",
    # ===================== v11.0 法力熔炉：欧米伽 (Manaforge Omega) — HEADLESS =====================
    "集能哨兵": "Plexus Sentinel",
    "节点之王萨哈达尔": "Nexus-King Salhadaar",
    "狩魂猎手": "The Soul Hunters",
    "弗兰克提鲁斯": "Fractillus",
    "熔炉编织者阿拉兹": "Forgeweaver Araz",
    "缚魂者娜欣达利": "Soulbinder Naazindhri",
    "诸界吞噬者迪门修斯": "Dimensius the All-Devouring",
    "卢米萨尔": "Loom'ithar",
    # ===================== v11.0 尼鲁巴尔王宫 (Palace of Nerub'ar) — HEADLESS =====================
    "苏雷吉队长席克兰": "Sik'ran, Captain of the Sureki",
    "流丝之庭": "The Silken Court",
    "安苏雷克女王": "Queen Ansurek",
    "节点女亲王凯维扎": "Nexus-Princess Ky'veza",
    "拉夏南": "Rasha'nan",
    "噬灭者乌格拉克斯": "Ulgrax the Devourer",
    "虫巢扭曲者欧维纳克斯": "Broodtwister Ovi'nax",
    "血缚恐魔": "Bloodbound Horror",
    # ===================== v11.0 解放安德麦 (Liberation of Undermine) — HEADLESS =====================
    "铬武大王加里维克斯": "Chrome King Gallywix",
    "穆格·兹伊安保头子": "Mug'Zee, Heads of Security",
    "独臂盗匪": "One-Armed Bandit",
    "链齿狂人洛肯斯多": "Sprocketmonger Lockenstock",
    "维克茜和磨轮": "Vexie and the Geargrinders",
    "里克·混响": "Rik Reverb",
    "斯提克斯·堆渣": "Stix Bunkjunker",
    "血腥大熔炉": "Cauldron of Carnage",
    # ===================== v12.0 进军奎尔萨拉斯 (March on Quel'Thalas) =====================
    "午夜陨落": "Midnight Falls",
    "贝洛伦，奥之子嗣": "Belo'ren, Child of Al'ar",
    # ===================== v12.0 孢陨幽境 (Sporefall Sanctum) =====================
    "腐沼": "The Rot",
    # ===================== v12.0 虚影尖塔 (Phantasmal Spire) =====================
    "光盲先锋军": "Lightblinded Vanguard",
    "宇宙之冠": "Crown of the Cosmos",
    "陨落之王萨哈达尔": "Fallen-King Salhadaar",
    "元首阿福扎恩": "Imperator Averzian",
    "威厄高尔和艾佐拉克": "Vaelgor & Ezzorak",
    "弗拉希乌斯": "Vorasius",
    # ===================== v12.0 梦境裂隙 (Dreamrift) =====================
    "奇美鲁斯，未梦之神": "Chimaerus the Undreamt God",
    # ===================== v12.1 潮缚石窟 (Tidebound Grotto) — HEADLESS =====================
    "尼姆瑞莎·唤波者": "Nimrissa the Wavecaller",
    # ===================== v12.1 烈毒之渊 (The Venomous Abyss) — HEADLESS =====================
    "乌拉特克": "Urathek",
    "迷失的探险者": "The Lost Explorers",
    "陵寝哨兵": "The Entombed Sentinels",
    "斯索拉克": "Sszorak",
    "盘卷祭坛": "The Coiled Altar",
    "盘魂者内克扎莉": "Nek'zali the Soulcoiler",
    "双子毒牙": "The Twin Fangs",
    "万毒邪祟者瓦什尼克": "Vashnik the Malignant",
}
