-- ============================================================================
-- BossTips 攻略翻译 —— 大秘境（enUS，仅译文；源文本见对应简中攻略文件）
-- 按游戏设置/客户端语言显示；缺失首领自动回退简中。
-- 难度键：大秘境=mythicplus；团本=lfr/normal/heroic/mythic。
-- ============================================================================
local _, addon = ...
addon.GuideData = addon.GuideData or { versions = {}, mplus = {}, raids = {}, meta = {}, mplusInfo = {}, versionInfo = {} }
addon.GuideData.translations = addon.GuideData.translations or {}
addon.GuideData.translations.enUS = addon.GuideData.translations.enUS or {}
addon.GuideData.translations.enUS.mplus = addon.GuideData.translations.enUS.mplus or {}
addon.GuideData.translations.enUS.mplus["Current"] = {
    ["虚空之痕竞技场"] = {
        ["煞戎努斯"] = { mythicplus = [=[{rt8}Charonus{rt8}||[Unstable Singularity] gravity collapse pulls in—don't get sucked to center (stand between holes to resist); [Gravity Orb] kite into a hole to delete, dodge lines||[Cosmic Smash] marked cast, [Void Torrent] channel—prioritize interrupt; new [Dark Wave] dodge by movement||Spread your purple circles; tank takes [Aggregated Mass]]=] },
        ["法术风暴拉杰克斯"] = { mythicplus = [[{rt8}Spellstorm Rajaxx{rt8}||[Disruption Orb] marks a player with a silence orb for 15s—lead it away from the group.||Multi-hit AoE spellstorm; on death grants the matching buff; the orb carrier stays 15s away from the group.]] },
        ["焦躁的虚镰"] = { mythicplus = [[{rt8}Restless Void Scythe{rt8}||[Corrosive Essence] now hits only 2 players (was 5), a 12s corruption DoT—must dispel or avoid overlap.||Those corrupted spread for 12s, healer pre-casts; grab the matching arena buff along the route.]] },
        ["防护龟壳守卫"] = { mythicplus = [[{rt8}Warding Turtle Guardian{rt8}||It channels a shield for a limited time; if the channel ends uninterrupted, it stuns itself and takes +10s increased damage (burn window).||Prioritize interrupting the channel to trigger the stun, then burst it down; one of the two new opening minibosses.]] },
        ["鲁莽监督者"] = { mythicplus = [[{rt8}Reckless Overseer{rt8}||[Brutal Smash] periodic damage -17% but still a heavy cleave/knockback.||Tank faces outward; raid DR during the smash; grab the matching buff.]] },
        ["吞噬暴虐者"] = { mythicplus = [[{rt8}Devouring Tyrant{rt8}||[Devour] channels (longer cast time makes interrupting/saving easier); the devour mechanic instantly kills the swallowed target.||Must interrupt Devour or rescue the swallowed; grab the buff along the route.]] },
        ["阿特洛苏斯"] = { mythicplus = [=[{rt8}Atroxus{rt8}||[Toxic Spit] 4s frontal cast—tank face out; [Venom Aura] raid-wide -10% healing + periodic damage, healer pre-cast||[Savage Roar] now a roar (no knockback) summoning [Venom Crawlers]—AoE fast; [Massive Claw] knockback + DoT; [Numbing Poison] -30% haste||Burn adds immediately; if cone targets you, lead it away, don't stand in poison]=] },
        ["塔兹拉尔"] = { mythicplus = [=[{rt8}Taz'Rah{rt8}||[Void Mimic] clones cast [Shadow Charge] (line = instant kill)—dodge; [Dark Rift] mine field, entering pulls you in and breaks formation||[Void Tear] marked circle cast—prioritize interrupt; [Cosmic Spike] tank-swap||Shadow-line marks keep to one side so charge paths don't overlap; dodge permanent purple circles and stray orbs]=] }
    },
    ["毒牙祭坛"] = {
        ["高阶进化者"] = { mythicplus = [[{rt8}High Evolutionary{rt8}||Dispel poison damage with poison dispel; if focus pressure is low, prioritize control.||{rt1}Must interrupt/kill fast: [Evolve]—interrupt the cast with CC, else [Envenom] becomes [Mass Envenom].{rt1}||[Envenom] is random—prioritize interrupts; healer be ready to dispel.]] },
        ["原始毒蛇"] = { mythicplus = [[{rt8}Primitive Serpent{rt8}||Spread to avoid [Foul Spit] splash; keep range.||{rt1}Must interrupt/kill fast: [Piercing Shriek]—interrupt every cast.{rt1}||Watch the poison damage; melee stay out of the spit circle.]] },
        ["双牙掠夺者"] = { mythicplus = [[{rt8}Twin-Fang Pillager{rt8}||Immune to CC; tank turns its front [Venom Breath] away from the group and soaks [Double Strike]'s heavy hit; [Deadly Shot] hits two players—magic dispel or freedom.||{rt1}Must interrupt/kill fast: no hard interrupt available.{rt1}||Stay spread to avoid breath hitting multiple; melee stand behind.]] },
        ["仪式首领"] = { mythicplus = [[{rt8}Ritual Leader{rt8}||Immune to CC; before engaging, destroy the Corrupted Mist totem to stop the [Unstable Totem] pulse; [Dissect] hits the tank—use a damage-reduction.||{rt1}Must interrupt/kill fast: [Blood Sacrifice] deals raid-wide damage and applies a heal absorb—pre-cast heals.{rt1}||Healer: watch the absorb shield; spell dispel is available.]] },
        ["扭缠盘蛇"] = { mythicplus = [=[{rt8}The Writhing Coil{rt8}||[Withering Venom] casts 3 in a row—assign interrupts; during [Death Rattle] everyone run out to snap [Vine Bonds] triggering [Uncoiled], focus the [Uncoiled Serpent] image||[Revenge Rush] dodge [Burrow Charge] lines, keep [Venom Spray] frontal away from group; kited player don't get bitten||Tank takes [Tail Blade]; healer cover [Synchronized Venom] stacking with [Death Rattle]]=] },
        ["拉维"] = { mythicplus = [=[{rt8}Rav'i{rt8}||Keep Boss away from carcass piles so it can't eat fresh meat and trigger [Gluttony]; during [Scavenge] everyone step in [Filthy Guests] to break shield fast||[Triple Shot] spread, dodge [Regurgitate] acid lines; tank takes [Water Smash] melee; healer watch [Carrion Burst] stacks||[Regurgitate] cleanses disease on hit; otherwise dodge rocks and big circles]=] },
        ["祖尔加"] = { mythicplus = [=[{rt8}Zul'jan{rt8}||During [Fang Ritual] 4 players stand on the line between snake-heads and Boss to soak [Ritual Venom] stacks; [Blood Sacrifice] clear stacks via physical hits (stand in [Bone Cleaver] axe path)||Drop the poison water at the edge; dodge [Bone Cleaver] axe paths and [Axe Polisher]'s 3 thrown axes||Tank [Sundering] opens with DR and drops a blood pool; healer cover [Fang Empower] stacks]=] },
        ["乌拉泰克的选民"] = { mythicplus = [[{rt8}Chosen of Ulataq{rt8}||When [Venom Surge] draws lines, dodge them and the healer covers the pulse damage; stay spread.||{rt1}Must interrupt/kill fast: [Mass Envenom]—interrupt every cast.{rt1}||Same-pack [Living Venom] explodes on death—stagger kills to give the healer breathing room.]] },
        ["晋升之蛇"] = { mythicplus = [[{rt8}Ascended Serpent{rt8}||Immune to CC; [Infected]—spread, then group up for AoE after [Hatched Serpents] spawn; avoid the [Venom Vortex] wind ring and keep [Venom Spray]'s front cone away from the group.||{rt1}Must interrupt/kill fast: [Altar Edge]—random targeted, always dodge.{rt1}||Tank faces [Venom Spray]'s knockback outward; healer covers poison damage.]] }
    },
    ["红玉新生法池"] = {
        ["深石塑地者"] = { mythicplus = [[{rt8}Deep Earthshaper{rt8}||Uninterruptible-channel [Earthsplitter] is a raid-wide AoE—stun or control it.||{rt1}Must interrupt/control: [Earthsplitter] hits 40 yards or wipes the raid.{rt1}||[Terraform] passively stacks a debuff; tank watch dragon eggs behind to avoid adds.]] },
        ["缚地守护者"] = { mythicplus = [[{rt8}Grounding Guardian{rt8}||[Grounding Brand] marks a random target—focus heal and cover with damage reduction.||{rt1}Must interrupt: don't miss its buff/control casts.{rt1}||Kill fast to reduce stacks.]] },
        ["毁灭唤风者"] = { mythicplus = [[{rt8}Destructive Windcaller{rt8}||[Lightning Storm] raid-wide AoE—pop DR; interrupt or spell-reflect fast casts.||{rt1}Must interrupt: lightning/thunder casts.{rt1}||Hold aggro on summoned adds.]] },
        ["大引导者莱瓦迪"] = { mythicplus = [[{rt8}Grand Conductor Rivazdi{rt8}||Door elite—must be killed to open the door; prioritize focus and interrupts.||{rt1}Must interrupt: high-threat casts (frost-channel type) don't miss.{rt1}||Raid-wide DR coverage; tank holds steady.]] },
        ["梅莉杜莎·寒妆"] = { mythicplus = [=[{rt8}Melidrussa Chillworn{rt8}||Stack to split [Frost Bolts] and rotate around the room; [Frigid Frostwind] marked run away from group to open space||[Frost Shard] must interrupt to reduce tank damage; at 66%/33% [Frost Barrier] spawns—break fast and kill the infused wyrmlings to prevent [Frost Overload]||Healer prioritize dispelling [Primordial Chill] stacks; dodge ice spikes, don't get knocked onto them by tornado]=] },
        ["基拉卡与厄克哈特·风脉"] = { mythicplus = [=[{rt8}Kyrakka and Erkhart Stormvein{rt8}||Open by bursting the dragon [Kil'ruk] down fast; position upwind to avoid being blown into fire||Humanoid [Eckhart] casting [Stormcrow Rain]—stop DPS; [Fel Fireblood Core] raid damage pop big DR, [Storm Strike] vulnerability dispel, [Roaring Breath] dodge line||Around 40% they merge—continue above, tanks rotate DR]=] },
        ["闪霜织寒者"] = { mythicplus = [[{rt8}Flashfrost Weaver{rt8}||Ranged interrupt [Frostbolt] to protect the tank; prioritize CC-kill.||{rt1}Must interrupt/dispel: [Ice Barrier]—else the target is CC-immune and shielded.{rt1}||With the barrier up, focus fire under damage-reduction coverage.]] },
        ["烈焰之咽"] = { mythicplus = [[{rt8}Flame Gullet{rt8}||Dodge [Flame Breath]'s front; tank pops DR for the [Flame Maw] DoT.||{rt1}Kill fast: below half health [Lava Blood] stacks make raid damage explode.{rt1}||Save cooldowns/bloodlust for after half health.]] },
        ["灰烬先知烈焰鞭笞者"] = { mythicplus = [[{rt8}Ashen Prophet{rt8}||[Flame Volley] channels and locks the tank—use control to interrupt the damage.||{rt1}Must control/dispel: on death it triggers [Flame Glory] leaving a fire circle—dispel or move away.{rt1}||]] },
        ["炎缚毁灭者"] = { mythicplus = [[{rt8}Flamebound Destroyer{rt8}||Immune to CC; leave the [Burnout] 20-yard explosion circle before it dies.||{rt1}Must interrupt: [Searing Strike]; walk away before [Living Bomb]'s knockback.{rt1}||[Infernal] raid-wide damage—tank pops DR.]] },
        ["柯姬雅·焰蹄"] = { mythicplus = [=[{rt8}Kokia Blazehoof{rt8}||At full energy [Ritual Bond] summons fire elementals; [Roaring Flame] must interrupt or wipe, [Searing Strike] must interrupt||Control fire pools clockwise; [Lava Rock] marked lead away from group, meteor rolls to open space—stay 20yd from [Burning End] before death||Tank opens DR on each [Searing Strike]]=] },
        ["雷霆之颅"] = { mythicplus = [[{rt8}Thunderous Skull{rt8}||Dodge [Storm Breath]'s front; tank pops DR against [Thunderous Bite]'s knockback.||{rt1}Must dispel correctly: [Rolling Thunder]—dispel only one stack; dispelling two at once wipes.{rt1}||]] }
    },
    ["密谋小径"] = {
        ["赞恩·刃悲"] = { mythicplus = [=[{rt8}Zaen Bladesorrow{rt8}||[Heartstopper Poison] tanks poison—dispel; [Flame Bomb] marked players touch [Fel-Infused Crates] to clear raid damage||[Chain Crime]/[Deadly Path] lines—each player hide behind a different crate as cover; [Killing Spree] is a raid-wide channel, pop DR||Use crates as cover, don't share one]=] },
        ["腐化术士"] = { mythicplus = [[{rt8}Corrupting Warlock{rt8}||Immune to CC.||{rt1}[Curse of Doom] random debuff (dispel or stack to share; a dead player summons a Doomguard).{rt1}||[Drain Life] marks a target—defend or drop combat.||Prioritize CC/interrupt on the doom bolt; dispel or share the curse promptly; before 50% it gains a Dark Pact shield—burn through it.]] },
        ["利希尔·烬怒"] = { mythicplus = [=[{rt8}Lishir{rt8}||[Chaos Bolt] random target must interrupt (top priority); opening [Felhunter] fixates tank—tank separates it from Boss||[Demon Portal] teleports then [Cataclysmic Tide] casts—take the safe side door, clear trash before tide to avoid +100% haste||[Fel Blast] use spare interrupts; [Burning Fel] pulses—watch positioning]=] },
        ["亵渎魔像"] = { mythicplus = [[{rt8}Defiled Golem{rt8}||Immune to CC.||{rt1}[Profane Smash] is a heavy channel—healer pre-cast.{rt1}||[Fel Beam] fires a line at each player leaving a puddle—dodge.||Found before the last boss; tank eats the smash with DR, raid dodges fel beams.]] },
        ["歼灭者萨祖克斯"] = { mythicplus = [=[{rt8}Xathuux the Annihilator{rt8}||[Axe Toss] marks then spawns [Legion Axes] at edge—burn immediately or AoE ramps (must-kill)||[Fel Strike] frontal—tank face out; during [Fel Frenzy] Boss leaves [Burning Stride] fel puddles—tank kites slowly along edge using less than half the room||Raid dodge landing zones, save DR for the damage amp]=] },
        ["希凡惩罚者"] = { mythicplus = [[{rt8}Shivan Punisher{rt8}||Immune to CC.||[Punishing Power] adds physical damage—tank beware; at 50% it triggers [Demoniac Frenzy] high pulse raid damage.||Dodge [Whirlwind] AoE; at 50% DPS burns it down before frenzy; tank pops DR.]] },
        ["酒馆打卡(五星级好评)"] = { mythicplus = [[{rt8}Tavern Check-in (Five-Star Review){rt8}||Forced event after boss 1: the 5-man disguises and climbs the spire; the whole group talks to Selenar to trigger it.||Each gets a random role (waiter/performer/cleaner/bodyguard); complete your role to fill the satisfaction meter to 5 stars.||The group gains [Five-Star Review] buff (+10% damage/healing ~4 min).||During it, [Harsh Review] casts spawn—any CC/interrupt makes them vanish; the route takes ~4 min.]] },
        ["凯斯媞亚·魔力之心"] = { mythicplus = [=[{rt8}Kystia Manaheart{rt8}||Open by focusing pet [Bitey]; below 20% it reverses control and applies 100% vulnerability—pop burn on Boss; [Fel Storm]/[Chaos Bolt] from mirror images must interrupt (top priority)||[Fel Nova] stomp; [Fel Breath] frontal cone—tank face away from group; when the drake turns hostile tank swap to it then back]=] }
    },
    ["纳洛拉克的洞穴"] = {
        ["纳洛拉克"] = { mythicplus = [=[{rt8}Nalorakk{rt8}||[Echoing Smash] marks 3 delayed echoes—drop mirages at outer edge/same corner, don't stand near or get ghost-slashed||[Overwhelming Assault] Zul'garath raises shield—group stands behind it for the 3 hits; [Warlord's Fury] group forms a wall to block echo charges||[Lightning Arrow] rotate interrupt, burst [Unstable Totem]; tank face away from echoes]=] },
        ["洛阿祭司娜妮娅"] = { mythicplus = [[{rt8}Loa Priestess Naniyah{rt8}||Immune to CC.||{rt1}[Lightning Bolt] random target—rotate interrupts; [Earthquake] two players drop circles; [Unstable Totem] persistent AoE.{rt1}||Keep the lightning-bolt interrupt chain; move out of Earthquake; kill the totem fast.]] },
        ["老练的战争使者"] = { mythicplus = [[{rt8}Veteran Warbringer{rt8}||Immune to CC.||[Primordial Echo] raid-wide AoE; [Poison Spear Volley] ground circles (3s projectile).||Healer pop DR; dodge poison-spear circles; no hard CC.]] },
        ["决意化身"] = { mythicplus = [[{rt8}Resolute Avatar{rt8}||Immune to CC.||[Frozen Tomb] roots the whole group—break it or use freedom; [Shatter] is a high-damage AoE.||Stay spread to avoid chained freezes; step out of Shatter circles immediately; use freedom/icebreak to clear the root.]] },
        ["饥荒雕像"] = { mythicplus = [[{rt8}Famine Statue{rt8}||Summoned by [Hungry Spirit], immune to CC.||Focus it on spawn or it repeatedly casts [Endless Hunger] (~5-6s cast applying a debuff).||Dispel the curse debuff; healer prepare for [Feast of Suffering] channel damage.]] },
        ["囤宝狂人"] = { mythicplus = [=[{rt8}The Hoardmonger{rt8}||[Resource Measures] empowers abilities at 90/70/40%; [Rotten Mushrooms] must be stomped within 12s or [Foul Eruption] wipes group (every circle needs a stomper)||Flesh→[Mighty Bellow] knockback + DoT group heal; Bone→[Bonepike Maul] dodge circles; [Toxic Spores] dispel||Tank center, otherwise dodge frontal cone and ground spikes]=] },
        ["寒冬哨兵"] = { mythicplus = [=[{rt8}Sentinel of Winter{rt8}||Floor is ice—movement slides; [Ice Storm] is a fixed 8s channel, 10yd around Boss is safe (hug Boss)||[Shattercold Core] spawns only 1 ice—keep [Winter's Veil] interrupted; [Frost Agony] DoT dispel fast||[Blizzard] group up to pull to a point then skirt around; on raid AoE step in white circles/snow to resist knockback]=] },
        ["寒冬暴雪"] = { mythicplus = [[{rt8}Winter Blizzard{rt8}||Immune to CC.||[Biting Blizzard] pulses until killed; [Winter Hall] pushes players.||Prioritize killing it to stop the zone blizzard; use snow-free cover to dodge the wind; snow mounds no longer cause slipping.]] }
    },
    ["塞塔里斯神庙"] = {
        ["精华污染者"] = { mythicplus = [[{rt8}Essence Purifier{rt8}||[Essence Interference] channels on the Devouring Eye—interrupt to preserve the eye-energy and open the door.||{rt1}Must interrupt: Essence Interference.{rt1}||Prioritize CC-kill; protect the player channeling the eye.]] },
        ["堕落的守护者"] = { mythicplus = [[{rt8}Fallen Guardian{rt8}||Immune to CC; [Earthstomp] is a 30-yard AoE + knockback—spread or hug the wall; [Shatter] the main tank soaks with damage reduction and takes increased damage.||{rt1}Must kill fast: uninterruptible; [Shatter] tank must pop DR.{rt1}||Focus fire; avoid hard-soaking when stacked with other big hits.]] },
        ["塞塔里斯的化身"] = { mythicplus = [=[{rt8}Avatar of Sethraliss{rt8}||Two phases: kill [Defiler] to lift healing lock, then heal the central Avatar to full to win; [Corrupted Life]/[Corruption Burst] orbs soaked by DPS walking in (healer don't)||[Twisted Hexxer] must interrupt [Flame Shock]; focus [Faithless Tormenter] and keep away from healer—below 25% the Avatar executes it for a heal, keep above 25% before finish||[Fallen Guardian] [Corrupting Strike] tank DR; in P2 clear the healer-chasing adds]=] },
        ["米利克萨"] = { mythicplus = [=[{rt8}Merektha{rt8}||[Serpentine Knot] roots 2 players—interrupt/stun to free and AoE them down fast; [Venom Spray] must interrupt, [Thundering Breath] move away to drop circle||Free teammates pinned by adds immediately; after [Burrow] kill hatched [Venomous Viper]/[Storm Adder], tank kites [Storm Adder] to edge for [Storm Catalyst] pool||[Lightning Bite] tank DR; after [Serpent Storm] knockback dodge ground circles, avoid Boss cross-path]=] },
        ["阿德里斯和阿斯匹克斯"] = { mythicplus = [=[{rt8}Adderis and Aspix{rt8}||[Stormshield] shield rotates—focus only the unshielded one; killing one enrages the other with [Frenzy], need DR + burst||[Gale Force] knockback then regroup mid to split [Thunder and Lightning]; tank hug wall to avoid being flung||[Breath of Storms] marks 2 to drop silence zones outside—nobody stand in them]=] },
        ["扭曲的妖术师"] = { mythicplus = [[{rt8}Twisted Hexxer{rt8}||[Lurking Hex] marks a player, drops a circle then turns them into a frog—move out of the group and avoid [Hex Mud]; [Flame Shock] is interruptible.||{rt1}Must interrupt: Flame Shock.{rt1}||Immune to CC; dispel [Lurking Hex] before it expires to prevent the frog.]] },
        ["无信征服者"] = { mythicplus = [[{rt8}Faithless Conqueror{rt8}||[Mind Disruption] randomly curses a player with confusion—interrupt or dispel to clear.||{rt1}Must interrupt: Mind Disruption.{rt1}||Watch healer pressure when stacked with [Shadow Lash].]] },
        ["流沙猎手"] = { mythicplus = [[{rt8}Quicksand Hunter{rt8}||[Arrow Barrage] channels on a random target—use CC/interrupt to stop the damage; dodge [Sandblast Arrow] landing circles.||{rt1}Must interrupt/kill fast: stop [Arrow Barrage]'s channel with CC or interrupt.{rt1}||CC it before pulling to avoid barrage stacking with other damage.]] },
        ["无信折磨者"] = { mythicplus = [[{rt8}Faithless Torturer{rt8}||Focus fire; it locks onto a healer and stacks [Shadow Lash] to reduce healing—kill it fast and away from the healer.||{rt1}Must kill fast: burn the healer-locking torturer before the healing debuff stacks.{rt1}||Below 25% the avatar executes it for a heal—keep it above 25% before finishing.]] },
        ["风暴飞蛇"] = { mythicplus = [[{rt8}Storm Viper{rt8}||[Storm Catalyst] leaves a thunder pool—everyone get out; tank pops damage reduction during [Serpent's Storm Call] buff.||{rt1}Must interrupt: Storm Catalyst (leaves pool damage).{rt1}||Pull the snake to the edge or onto existing poison to reduce field clutter.]] },
        ["剧毒蝰蛇"] = { mythicplus = [[{rt8}Venomous Viper{rt8}||[Venom Spray] targets a random player—interrupt to avoid stacking poison; [Cell Poison] use poison cleanse or damage reduction.||{rt1}Must interrupt: Venom Spray.{rt1}||Keep poison pools away from the group; healer watch targeted poison damage.]] },
        ["加瓦兹特"] = { mythicplus = [=[{rt8}Galvazzt{rt8}||[Lightning Spire] spawns 3 each time; non-tank DPS stand between Boss and spire to block beams and stop charging; at full energy [Charged Burst] is near-wipe—all 3 beams must be blocked every wave||[Shock] tank kites Boss along the edge dropping water; [Shock Field] lands—everyone out of circle; rotate beam-soakers (take [Shock] vulnerability, don't soak twice)]=] }
    },
    ["夺目谷"] = {
        ["护光者鲁伊亚"] = { mythicplus = [=[{rt8}Light Warden Ruia{rt8}||Three phases: owl (100-70)→bear (70-40)→Halycon (below 40); [Guardian's Wrath] must interrupt||Owl [Holy Fire] marks 3 for 6s burn then spawns [Holy Fire Beam] (silence); marked 3 spread early, stack then leave same direction at expiry||Bear [Shatterstrike] cone stacks vulnerability, [Savage Maul] bleed must be healed full—3 players spread so cones don't overlap; below 40% is a hard heal check]=] },
        ["薯蛙母"] = { mythicplus = [[{rt8}Taro Frogmother{rt8}||Immune to CC.||[Tongue Toss] flings the tank (terrain-kill risk); [Venom Spit] raid poison DoT; [Lay Eggs] hatches [Newtlings] (knockback).||Tank stay away from platform edge when tossed; healer dispel poison; AoE the eggs instantly so they don't hatch.]] },
        ["圣光猎手伊库兹"] = { mythicplus = [=[{rt8}Ikuzz the Light Hunter{rt8}||At full energy [Bloodthirsty Gaze] locks 1 player for 10s; the hunted runs along [Bloodthorn Roots] using Boss like a lawnmower to crush them (stepping on = rooted); [Verdant Stomp] knocks back then grows roots under everyone—cleave the roots at your feet||At 50% [Lightfrenzied] spikes movement—burn it down; others dodge thorns and don't get stomped into danger]=] },
        ["兹欧凯特"] = { mythicplus = [=[{rt8}Zikket{rt8}||[Bloom Essence] orbs drift toward Boss—soak all, never let Boss eat them (else shield + Radiant Burst); [Awakened Bloom] summons [Bloom Lashes]—push to dormant then finish with [Focused Light] to clear [Luminous Resin]||[Sapwood] pulses raid-wide; pull Boss to platform edge so resin doesn't clutter center||Prioritize interrupting/stunning adds that spawn]=] },
        ["光明众花"] = { mythicplus = [=[{rt8}Lightbloom Trinity{rt8}||Three share hp—AoE all together; [Light Arrow]/[Radiant Slash] must interrupt||[Bedrock Crusher] spawns [Fertile Soil]/[Blinding Light Bloom] beams—someone must stand in the beam/circle to block light or the flower stacks [Light Devoured] (+15% dmg/stack); tank + 2 step into circle first||[Thornblade] marks then [Thornfan] hits 3x/sec—marked player run out before popping DR]=] },
        ["翠绿林地守卫"] = { mythicplus = [[{rt8}Verdant Grove Guardian{rt8}||Immune to CC.||[Earthrend] marks the tank leaving a puddle; [Uproot] AoE heavy hit + knockback.||Tank drops the puddle outside the group; don't stand near cliffs/roots before the knockback.]] },
        ["灌木潜行者"] = { mythicplus = [[{rt8}Bramble Stalker{rt8}||[Thornblade] marks a random target with heavy bleed (8s).||Focus heal / clear bleed / personal damage reduction.]] },
        ["疯长多头蛇"] = { mythicplus = [[{rt8}Rampant Hydra{rt8}||Immune to CC.||[Lightjaw Beam] channels 3 random targets (line hurts allies); [Seed Volley] line marks.||Three spread outward so the beam doesn't cross allies; use vanish/shadowmeld to drop combat and avoid it; dodge lines.]] },
        ["迷乱尖啸者"] = { mythicplus = [[{rt8}Maddening Shrieker{rt8}||{rt1}[Maddening Screech]—interrupt every time (group confuse).{rt1}||Assign a fixed interrupt, offset from Light Arrow Volley.]] },
        ["光耀播法者"] = { mythicplus = [[{rt8}Radiant Caster{rt8}||{rt1}[Light Arrow Volley]—interrupt every time; at low blood it [Awakens the Grove] summoning nearby dormant lashers.{rt1}||Top interrupt priority raid-wide; at low blood CC+focus so it can't awaken the grove.]] },
        ["噬光鞭笞者"] = { mythicplus = [[{rt8}Light-Devouring Lasher{rt8}||After gaining [Bloom Pollen] it gets a shield and is empowered.||Immediately switch to break the shield, then return to the main target.]] }
    },
    ["诸王之眠"] = {
        ["祖尔的暗影"] = { mythicplus = [[{rt8}Zul's Shadow{rt8}||Tank eats [Shadow Barrage] (uninterruptible, non-stacking DoT); [Dark Revelation]—move away from allies and stand in a [Dark Pool] to avoid raid damage.||{rt1}Cleanse: the summoned Zul's minions' [Shadow Bind] must be dispelled/bubble broken instantly or it's fatal.{rt1}||In 12.1 there are 2 Dark Pools—two players permanently soak them.]] },
        ["始皇达萨"] = { mythicplus = [=[{rt8}King Dazar{rt8}||[Earthshaking Leap] marks and jumps to players—marked run out and DR; [Blade Combo] last two hits tank DR||At 80% [Reban] spawns—don't stand in dragon front; at 60% mounts [Tizala] with [Eternal Guardian] damage transfer—focus||[Deadly Roar] fear must interrupt / [Impaling Spear] stun must dispel||At 40% [Spear Launcher] chases clockwise—move counterclockwise to jump spears; leave [Gilded Annihilation] landing zones immediately]=] },
        ["部族议会"] = { mythicplus = [=[{rt8}Council of Tribes{rt8}||Spread to dodge [Lightning Arc]/[Charge]; tank DR on [Enfeebling Backhand]; in the hall kill Healing Tide Totem first||[Poison Nova] must interrupt; [Explosive Totem] ([Elemental Summon]) wipes on land—burst first||[Whirling Axes] step out of melee; dead bosses keep casting as spirits—stack when soak prompt appears]=] },
        ["活化守卫"] = { mythicplus = [[{rt8}Animated Guardian{rt8}||Tank faces it away from the group; everyone attacks from the side/back to avoid the front [Suppressing Smash] cone stun.||{rt1}Watch: [Release Inhibitor] grants +75% attack speed—switch or stun during the cast.{rt1}||In 12.1 the entrance guards moved back; pull one at a time to avoid chained frontals.]] },
        ["黄金风蛇"] = { mythicplus = [=[{rt8}The Golden Serpent{rt8}||[Fortune's Call] gold sludge crawls—kill the Animated Gold before it reaches Boss or Boss stacks shield + damage buff; avoid [Spit Gold]/[Molten Gold] puddles and their crawl paths||Two players spat on stack the puddles together; floor turning to slime—burn it before it touches Boss||Tank away from edges/gong; [Serpent Tail Smash] DR, [Serpent Gale] away from cliff to avoid knockback]=] },
        ["幻影萨满祭司"] = { mythicplus = [[{rt8}Phantom Shaman{rt8}||Prioritize interrupting casts; spread to avoid chain CC; mages don't steal its buff.||{rt1}Must interrupt: [Hex] (sheep)—dispel the target immediately after it lands.{rt1}||Melee watch controlled targets and cleanse them together with Zul's minions.]] },
        ["祖尔的爪牙"] = { mythicplus = [[{rt8}Zul's Minion{rt8}||[Shadow Bind] shield—cleanse/dispel magic kills it instantly, the fastest solution.||{rt1}Cleanse: [Shadow Bind]; on landing [Despairing Abyss] fears—dispel the healer.{rt1}||In 12.1 a new [Gaze] beam locks a target for 10s; the marked player creates distance.]] },
        ["木乃伊"] = { mythicplus = [[{rt8}Mummy{rt8}||Both half-done and finished mummies cast [Wretched Eruption] (nature raid sickness); kill fast to reduce burden.||{rt1}Must interrupt: [Wretched Eruption] (12s party disease).{rt1}||Prioritize the finished mummies Mchimba summons from wrong coffins to avoid snowballing.]] },
        ["殓尸者姆沁巴"] = { mythicplus = [=[{rt8}Mchimba the Embalmer{rt8}||Healer sustains [Drained] targets—above 90% hp lifts [Withered]; keep [Burning Decay] fire off coffin spots||Mummies [Wretched Eruption] must interrupt; [Buried] shows struggle prompt—open the right coffin, rescue first then clear mummies||Tank avoid fire, DPS burst released mummies]=] }
    }
}
